name: KeepAlive

on:
  schedule:
    - cron: "0 0 1 * *" # every 1st day of the month at 00:00(UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git switch -C keepalive
      - run: git commit --allow-empty -m "monthly keepalive $(date -u +%F) [skip ci]"
      - run: git push -f origin keepalive
